---
title: "Demo R Notebook for Simulated Gene Expression"
output: html_notebook
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Create a 5x10 matrix of random integers
```{r}
gene_expression <- matrix(sample(1:500, 5 * 10, replace = TRUE), nrow = 5)
```

# Define column names as cond1, cond2, cond3, cond4, cond5, ctrl1, ctrl2, ctrl3, ctrl4, ctrl5
```{r}
colnames(gene_expression) <- c("cond1", "cond2", "cond3", "cond4", "cond5", "ctrl1", "ctrl2", "ctrl3", "ctrl4", "ctrl5")
gene_expression
```

# Define row names as gene1, gene2, gene3 ...
```{r}
rownames(gene_expression) <- c("gene1", "gene2", "gene3", "gene4", "gene5")
gene_expression
```

# Compute the fold change for each gene.
```{r}
calculate_fold_change <- function(data) {
  # Extract condition values and calculate their mean
  condition_values <- data[, 1:5] 
  condition_means <- rowMeans(condition_values)
  
  # Extract control values and calculate their mean
  control_values <- data[, 6:10] # Columns 7 to 11 are for controls
  control_means <- rowMeans(control_values)
  
  # Calculate fold change: condition mean / control mean
  fold_changes <- condition_means / control_means
  
  # Combine gene identifiers with their corresponding fold changes
  result <- data.frame(fold_change=fold_changes)
  
  return(result)
}

calculate_fold_change(gene_expression)
```

